gamecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path 
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('games/', views.games_index, name='index'),
    path('games/create/', views.GameCreate.as_view(), name='games_create'),
    path('games/<int:game_id>/', views.games_detail, name='detail'),
    path('games/<int:game_id>/add_review/', views.add_review, name='add_review'),
    path('games/<int:pk>/update', views.GameUpdate.as_view(), name='games_update'),
    path('games/<int:pk>/delete', views.GameDelete.as_view(), name='games_delete'),
    path('collectibles/', views.CollectibleList.as_view(), name='collectibles_index'),
    path('collectibles/<int:pk>/', views.CollectibleDetail.as_view(), name='collectibles_detail'),
    path('collectibles/create/', views.CollectibleCreate.as_view(), name='collectibles_create'),
    path('collectibles/<int:pk>/update/', views.CollectibleUpdate.as_view(), name='collectibles_update'),
    path('collectibles/<int:pk>/delete/', views.CollectibleDelete.as_view(), name='collectibles_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
# Create your models here.
SCORES = (
    ('P', 'Poor'),
    ('A', 'Average'),
    ('O', 'Outstanding')
)

class Collectible(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('collectibles_detail', kwargs={'pk': self.id})
        


class Game(models.Model):
    name = models.CharField(max_length= 250)
    genre = models.CharField(max_length=250)
    description = models.TextField(max_length=500)
    collectibles = models.ManyToManyField(Collectible)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'game_id': self.id})
    

class Reviews(models.Model):
    date = models.DateField('review date')
    score = models.CharField(
        max_length=1,
        choices=SCORES,
        default=SCORES[1][1]
    )
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    def __str__ (self):
        return f"{self.get_score_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Reviews

class ReviewsForm(ModelForm):
    class Meta:
        model = Reviews
        fields = ['date', 'score']

main_app/views.py
from django.shortcuts import render, redirect

from django.views.generic import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Game, Collectible
from .forms import ReviewsForm


# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')






def games_index(request):
    games = Game.objects.all()
    return render(request, 'games/index.html', { 'games': games })




def games_detail(request, game_id):
    game = Game.objects.get(id=game_id)
    reviews_form = ReviewsForm()
    return render(request, 'games/detail.html', {'game': game, 'reviews_form': reviews_form})

def add_review(request, game_id):
    form = ReviewsForm(request.POST)
    if form.is_valid():
        new_review = form.save(commit=False)
        new_review.game_id = game_id
        new_review.save()
    return redirect('detail', game_id=game_id)

class GameCreate(CreateView):
    model = Game
    fields = '__all__'
    success_url = '/games/'


class GameUpdate(UpdateView):
    model = Game
    fields = ['genre', 'description']

class GameDelete(DeleteView):
    model = Game
    success_url ='/games/'


class CollectibleList(ListView):
    model = Collectible


class CollectibleDetail(DetailView):
    model = Collectible

class CollectibleCreate(CreateView):
    model = Collectible
    fields = '__all__'

class CollectibleUpdate(UpdateView):
  model = Collectible
  fields = '__all__'

class CollectibleDelete(DeleteView):
  model = Collectible
  success_url = '/collectibles/'

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

<h1>About the Game Collector</h1>
<hr />
<p>Largest Digital Game Collection website!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Game Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="/" class="left brand-logo">&nbsp;&nbsp;GameCollector</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li>
              <a href="{% url 'collectibles_create' %}">Add a Collectible</a>
            </li>
            <li>
              <a href="{% url 'collectibles_index' %}">View All Collectibles</a>
            </li>
            <li><a href="{% url 'games_create' %}">Add a Game</a></li>
            <li><a href="{% url 'index' %}"> View All My Games</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">
        All Rights Reserved, &copy; 2023 Game Collector &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/games/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Game Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ game.name }}</span>
        <p>Genre: {{ game.genre }}</p>
        <p>Description: {{ game.description }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'games_update' game.id %}">Edit</a>
        <a href="{% url 'games_delete' game.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_review' game.id %}" method="post">
      {% csrf_token %} {{ reviews_form.as_p }}
      <input type="submit" class="btn" value="Add Review" />
    </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Score</th>
        </tr>
      </thead>
      <tbody>
        {% for reviews in game.reviews_set.all %}
        <tr>
          <td>{{reviews.date}}</td>
          <td>{{reviews.get_score_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ game.name }}'s Toys</h3>
    {% if game.collectibles.count %}
      {% for collectible in game.collectibles.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A {{ collectible.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Collectibles :(</h5>
    {% endif %}
  </div>
</div>

<script>
  const dateEl = document.getElementById("id_date");
  M.Datepicker.init(dateEl, {
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  });

  const selectEl = document.getElementById("id_score");
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/games/index.html
{% extends 'base.html' %} {% block content %}

<h1>Game List</h1>

{% for game in games %}
<div class="card">
  <a href="/games/{{game.id}}">
    <div class="card-content">
      <span class="card-title">{{ game.name }}</span>
      <p>Genre: {{ game.genre }}</p>
      <p>Description: {{ game.description }}</p>
    </div>
  </a>
</div>
{% endfor %} {% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/collectible_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Collectible</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'collectibles_detail' object.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/collectible_detail.html
{% extends 'base.html' %} {% block content %}

<h1>Collectible Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ collectible.name }}</span>
      </div>
      <div class="card-action">
        <a href="{% url 'collectibles_update' collectible.id %}">Edit</a>
        <a href="{% url 'collectibles_delete' collectible.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/collectible_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Collectible</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/main_app/collectible_list.html
{% extends 'base.html' %} {% block content %}

<h1>Collectible List</h1>

{% for collectible in collectible_list %}
<a href="{% url 'collectibles_detail' collectible.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ collectible.name }}</span>
    </div>
  </div>
</a>
{% endfor %} {% endblock %}

main_app/templates/main_app/game_confirm_delete.html
{% extends 'base.html' %} {% block content %}

<h1>Game Delete</h1>

<h4>
  Are you sure you want to delete <span class="teal-text">{{object.name}}</span>
</h4>

<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete this Game" class="btn red" />
  <a href="{% url 'detail' game.id %}">No - Take me back</a>
</form>

{% endblock %}

main_app/templates/main_app/game_form.html
{% extends 'base.html' %} 

{% block content %} 

{% if not object %}
<h1>Add a Game</h1>
{% else %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% endif %}

<form action="" method="post">
  {% csrf_token %}
  <table>
    {{form.as_table}}
  </table>
  <input type="submit" value="Save" class="btn" />
</form>

{% endblock %}